version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    restart: on-failure
    ports:
      - "8001:8000"
    volumes:
      - ./app:/fast_graph/app
      - ./main.py:/fast_graph/main.py
    depends_on:
      - db

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "fast_graph"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "54321:5432"